
# see https://www.researchgate.net/publication/259179064_Comparing_Methods_for_Detecting_Child_Exploitation_Content_Online for common CSAM words
# http://antipaedo.lip6.fr/T12/keywords_cnrs.pdf - for top 20 from table 7 and 8 of the paper, plus other similar words , ignoring stopwords like "tuesday"
# WARNING: Translations are probably not accurate. TODO to fix.
# we are only doing our current covered langauges. TODO, do for all languages.
banned_words = {
    'ar': {
        "فتاة صغيرة",
        "فتى صغير",
        "مراهق",
        "لولا",
        "لوليتا",
        "لولي",
        "لوليتاغوي",
        "فتاة",
        "صبي",
        "طفل",
        "حمام",
    },
    'ur': {
        'نوجوان لڑکی',
        'چھوٹی لڑکی',
        'چھوٹا لڑکا',
        'نوجوان لڑکا',
        'نوعمر',
        'لولا',
        'لولیتا',
        'لولی',
        'لولیتاگو',
        'لڑکی',
        'لڑکا',
        'بچہ',
        'غسل',
    },
    'bn': {
        'ছোট মেয়ে',
        'ছোট ছেলে',
        'কিশোর',
        'লোলা',
        'ললিতা',
        'ললি',
        'লোলি',
        'ললিটাগুই',
        'মেয়ে',
        'ছেলে',
        'শিশু',
        'স্নান',
    },
    'hi': {
        'युवा लड़की',
        'छोटी लड़की',
        'छोटा लड़का',
        'किशोर',
        'लॉली',
        'लोला',
        'लोलिता',
        'लल्ली',
        'लोली',
        'लोलितागुय',
        'लड़की',
        'लड़का',
        'बच्चा',
        'स्नान',
    },
    'eu': {
        'neska gaztea',
        'neska txikia',
        'mutil txikia',
        'nerabea',
        'neska',
        'mutil',
        'haurra',
        'bainua',
    },
    'ca': {'noia', 'nena', 'nen petit', 'nen', 'banyer'},
    'vi': {
        'thiếu niên',
        'cậu nhỏ',
        'cô gái trẻ',
        'cô bé',
        'cậu bé',
        'trẻ em',
        'tắm',
    },
    'zh': {
        '儿童',
        '女孩',
        '孩子',
        '小女孩',
        '小姑娘',
        '小男孩',
        '年輕女孩',
        '年轻女孩',
        '年轻的女孩',
        '洗澡',
        '洛丽塔',
        '洛麗塔',
        '浴',
        '男孩',
        '萝拉',
        '萝莉',
        '萝莉塔吉',
        '蘿拉',
        '蘿莉',
        '蘿莉塔',
        '青少年',
    },
    'fr': {
        'jeune fille',
        'petite fille',
        'petit garçon',
        'ado',
        'fille',
        'garçon',
        'enfant',
        'bain',
    },
    'id': {
        'gadis muda',
        'gadis kecil',
        'anak laki-laki kecil',
        'remaja',
        'perempuan',
        'laki-laki',
        'anak',
        'mandi',
    },
    'fa': {
        'دختر جوان',
        'دختر کوچولو',
        'پسر کوچولو',
        'نوجوان',
        'لولا',
        'لولیتا',
        'لولی',
        'لولیتاگو',
        'دختر',
        'پسر',
        'کودک',
        'حمام',
    },
    'es': {
        'niña',
        'niño',
        'adolescente',
        'baño',
    },
    'pt': {
        'menina',
        'menino',
        'adolescente',
        'pirulito',
        'criança',
        'banho',
    },
    'ig': {' iri na ụma', 'nwa agbọghọ', 'nwoke', 'nwa'},
    'sw': {'msichana mdogo', 'kijana mdogo', 'mtoto', 'kuoga'},
    'yo': {
        'kekere',
        'omobinrin',
        'omokunrin',
        'ọmọ',
        'wẹwẹ',
    },
    'xh': {
        'intombazana encinci',
        'intsha',
        'umntwana',
        'hlamba',
        'inkwenkwe',
    },
    'zu': {
        'intombazane',
        'intsha',
        'intombazane encane',
        'umfana omncane',
        'geza',
        'ingane',
        'yomfana',
    },
    'default': {
        'young girl',
        'little girl',
        'little boy',
        'young boy',
        'teen',
        'lolli',
        'lola',
        'lolita',
        'lolly',
        'loli',
        'lolitaguy',
        'girl',
        'boy',
        'child',
        'kid',
        'bath',
        'baths',
        'bathing',
        "pedo",
        'nymphet',
        'nimphet',
        'babyj',
        'voglia',
        'eurololita',
        '349',
        'hussyfan',
        'raygold',
        'ygold',
        'qwerty',
        'qqaazz',
        'ptsc',
        'pthc',
        'nn',
        'tanta',
        'mylola',
        'arina',
        'newstar',
        'playtoy',
        'imouto',
        'lourinha',
        'amateurz',
        'kacy',
        'vicky',
        'lsm',
        'sandra',
        'babyshivid',
        'shiori',
        'tvg',
        'chiharu',
        'kidzilla',
        'izzy',
        'rika',
        'kdquality',
        'cbaby',
        'nablot',
        'lso',
        'kinderficker',
        'yo',
        'yr',
    },
}
